[0m13:44:15.911969 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000299D2264E00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000299D2265190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000299D22662D0>]}


============================== 13:44:15.927088 | e1a58331-d080-4c0f-8c28-e3fd99b2ba07 ==============================
[0m13:44:15.927088 [info ] [MainThread]: Running with dbt=1.9.6
[0m13:44:15.927088 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Administrador\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt init', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m13:44:45.137807 [debug] [MainThread]: Starter project path: C:\Users\Administrador\OneDrive\Escritorio\venv\Lib\site-packages\dbt\include\starter_project
[0m13:44:45.188036 [info ] [MainThread]: 
Your new dbt project "nu_analytics_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m13:44:45.189067 [info ] [MainThread]: Setting up your profile.
[0m13:46:31.294686 [info ] [MainThread]: Profile nu_analytics_project written to C:\Users\Administrador\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m13:46:31.294686 [debug] [MainThread]: Command `dbt init` succeeded at 13:46:31.294686 after 135.52 seconds
[0m13:46:31.294686 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000299D47F8980>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000299D4088BC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000299D44E93A0>]}
[0m13:46:31.294686 [debug] [MainThread]: Flushing usage events
[0m13:46:31.851956 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m20:56:51.030275 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019CA8B1D4C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019CA8B1FEC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019CA55EF710>]}


============================== 20:56:51.046267 | 19aea9fa-a057-47cb-b070-deb59ff320f6 ==============================
[0m20:56:51.046267 [info ] [MainThread]: Running with dbt=1.9.6
[0m20:56:51.046267 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\Administrador\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt deps', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m20:56:51.046267 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Administrador\OneDrive\Escritorio\nu_dw_snowflake_dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:56:51.046267 [debug] [MainThread]: Command `dbt deps` failed at 20:56:51.046267 after 0.26 seconds
[0m20:56:51.046267 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019CA8F18140>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019CAA5C7FE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019CAA5C77A0>]}
[0m20:56:51.046267 [debug] [MainThread]: Flushing usage events
[0m20:56:51.730729 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m20:58:01.326772 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002921DED10A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002921B11F7A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002921B72D160>]}


============================== 20:58:01.342546 | 2e299970-48fd-4afe-89e0-b57d3d903870 ==============================
[0m20:58:01.342546 [info ] [MainThread]: Running with dbt=1.9.6
[0m20:58:01.342546 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\Administrador\\.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt deps', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m20:58:01.342546 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Administrador\OneDrive\Escritorio\nu_dw_snowflake_dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:58:01.342546 [debug] [MainThread]: Command `dbt deps` failed at 20:58:01.342546 after 0.14 seconds
[0m20:58:01.342546 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002921DE62F60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002921DFA5CD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002921B11F7A0>]}
[0m20:58:01.342546 [debug] [MainThread]: Flushing usage events
[0m20:58:02.091857 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m20:59:21.124946 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028C94E558E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028C94D14530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028C94E56F00>]}


============================== 20:59:21.124946 | 4b4f1632-9f15-4558-a578-eae6dcccf8d0 ==============================
[0m20:59:21.124946 [info ] [MainThread]: Running with dbt=1.9.6
[0m20:59:21.124946 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\Administrador\\.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt deps', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m20:59:21.124946 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Administrador\OneDrive\Escritorio\nu_dw_snowflake_dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:59:21.124946 [debug] [MainThread]: Command `dbt deps` failed at 20:59:21.124946 after 0.14 seconds
[0m20:59:21.124946 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028C94FA6480>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028C94A6E390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028C94B3BD70>]}
[0m20:59:21.124946 [debug] [MainThread]: Flushing usage events
[0m20:59:22.358518 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m21:01:37.703059 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002032B64AA80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002032EA21640>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002032EA21700>]}


============================== 21:01:37.703059 | 634f7527-f0f4-4e9d-8b33-f38ad6e69e7a ==============================
[0m21:01:37.703059 [info ] [MainThread]: Running with dbt=1.9.6
[0m21:01:37.703059 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\Administrador\\.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt deps', 'send_anonymous_usage_stats': 'True'}
[0m21:01:37.703059 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Administrador\OneDrive\Escritorio\nu_dw_snowflake_dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:01:37.703059 [debug] [MainThread]: Command `dbt deps` failed at 21:01:37.703059 after 0.18 seconds
[0m21:01:37.703059 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000203304C7800>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002032EEA6870>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002032E9C9550>]}
[0m21:01:37.703059 [debug] [MainThread]: Flushing usage events
[0m21:01:38.202127 [debug] [MainThread]: An error was encountered while trying to flush usage events
